# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(329, 217)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.transfer_button = QtWidgets.QPushButton(self.centralwidget)
        self.transfer_button.setGeometry(QtCore.QRect(100, 160, 71, 23))
        self.transfer_button.setObjectName("transfer_button")
        self.anki_connection = QtWidgets.QLabel(self.centralwidget)
        self.anki_connection.setEnabled(False)
        self.anki_connection.setGeometry(QtCore.QRect(100, 90, 111, 23))
        self.anki_connection.setObjectName("anki_connection")
        self.connect_again = QtWidgets.QPushButton(self.centralwidget)
        self.connect_again.setEnabled(True)
        self.connect_again.setGeometry(QtCore.QRect(20, 120, 289, 23))
        self.connect_again.setAutoFillBackground(False)
        self.connect_again.setObjectName("connect_again")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 60, 136, 20))
        self.comboBox.setObjectName("comboBox")
        self.label_current_file = QtWidgets.QLabel(self.centralwidget)
        self.label_current_file.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_current_file.setFont(font)
        self.label_current_file.setObjectName("label_current_file")
        self.current_file_name_box = QtWidgets.QLabel(self.centralwidget)
        self.current_file_name_box.setGeometry(QtCore.QRect(20, 30, 291, 21))
        self.current_file_name_box.setText("")
        self.current_file_name_box.setObjectName("current_file_name_box")
        self.ok_label = QtWidgets.QLabel(self.centralwidget)
        self.ok_label.setGeometry(QtCore.QRect(200, 170, 54, 12))
        self.ok_label.setObjectName("ok_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 329, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_XMind_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_XMind_file.setObjectName("actionOpen_XMind_file")
        self.actionCreate_New_Deck = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_Deck.setObjectName("actionCreate_New_Deck")
        self.menu_file.addAction(self.actionOpen_XMind_file)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        self.actionOpen_XMind_file.triggered.connect(MainWindow.button_clicked)
        self.connect_again.clicked.connect(MainWindow.connect_anki)
        self.actionCreate_New_Deck.triggered.connect(MainWindow.create_new_deck)
        self.transfer_button.clicked.connect(MainWindow.transfer_notes_to_anki)
        self.comboBox.currentTextChanged['QString'].connect(MainWindow.select_deck)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.transfer_button.setText(_translate("MainWindow", "Transfer"))
        self.anki_connection.setText(_translate("MainWindow", "Anki is not opened."))
        self.connect_again.setText(_translate("MainWindow", "Connect Again"))
        self.label.setText(_translate("MainWindow", "Select Deck:"))
        self.label_current_file.setText(_translate("MainWindow", "Current File:"))
        self.ok_label.setText(_translate("MainWindow", "OK!"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_XMind_file.setText(_translate("MainWindow", "Open XMind file"))
        self.actionCreate_New_Deck.setText(_translate("MainWindow", "Create New Deck"))
